name: Build LMMS Snap

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build-snap:
    runs-on: ubuntu-24.04
    timeout-minutes: 90

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build snap
        uses: snapcore/action-build@b391f430cb2650fd359ed4d2cfe88b2c481800e0
        with:
          snapcraft-args: --destructive-mode

      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: lmms-snap
          path: "*.snap"
          if-no-files-found: error
